### PR TITLE
Update and sync dependencies. Fixes Gopkg.lock sync error

### PR DESCRIPTION
**Pull request by PhilipGough**
Fix lock file sync issue.

### CODE REVIEW

**Comment by mikz** [comment]
@PhilipGough what was the error and how you fixed it?

**Comment by PhilipGough** [comment]
@mikz 

Error: 
```bash
dep check
# Gopkg.lock is out of sync:
github.com/openshift/api/apps/v1: imported or required, but missing from Gopkg.lock's input-imports
github.com/openshift/api/route/v1: imported or required, but missing from Gopkg.lock's input-imports
github.com/operator-framework/operator-sdk/commands/operator-sdk: imported or required, but missing from Gopkg.lock's input-imports
github.com/operator-framework/operator-sdk/pkg/sdk: imported or required, but missing from Gopkg.lock's input-imports
github.com/operator-framework/operator-sdk/pkg/util/k8sutil: imported or required, but missing from Gopkg.lock's input-imports
github.com/operator-framework/operator-sdk/version: imported or required, but missing from Gopkg.lock's input-imports
github.com/sirupsen/logrus: imported or required, but missing from Gopkg.lock's input-imports
k8s.io/api/core/v1: imported or required, but missing from Gopkg.lock's input-imports
k8s.io/apimachinery/pkg/apis/meta/v1: imported or required, but missing from Gopkg.lock's input-imports
k8s.io/apimachinery/pkg/runtime: imported or required, but missing from Gopkg.lock's input-imports
k8s.io/apimachinery/pkg/runtime/schema: imported or required, but missing from Gopkg.lock's input-imports
k8s.io/apimachinery/pkg/util/intstr: imported or required, but missing from Gopkg.lock's input-imports
```

Fix: 
`dep ensure -update`

Perhaps I didn't need to pass the update flag but I ran the integration tests locally and all is good so figured it is no harm.

**Comment by mikz** [comment]
@PhilipGough I think it should be without the update, so we can see what was broken and then do the update in a different commit.

Updating frequently can be useful to prevent big bang changes, but also can introduce silent issues because we don't have test coverage. There are nice automated PR tools to update dependencies in Ruby, maybe there are some for Go too.

**Comment by PhilipGough** [comment]
@mikz Have modified the commit which now is the result of `dep ensure`. Will I do the update in another commit or do you feel this is needed now?

**Comment by mikz** [comment]
@PhilipGough I'd like to set up some automated tool to update dependencies, like dependabot, depfu, greenkeeper, ..., but I could not find one for go.

Regarding coverage. I think it is important to focus on the integration tests and gather coverage from there. Unit testing at this stage can be more of a burden than a safety net. 
https://blog.cloudflare.com/go-coverage-with-external-tests/
https://www.cyphar.com/blog/post/20170412-golang-integration-coverage

**Pull request merged**
